import { useMemo, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { api } from "../../lib/api";
import { useHeartbeat } from "../../hooks/use-presence";

/**
 * Scope Discovery admin review queue. Surfaces two independent
 * scope-expansion signals:
 *
 *   1. **Flywheel historical discovery** — wells seen across 3 years
 *      of dispatch (PropX + Logistiq + ES Express) that v2 doesn't
 *      have in its master. Generated by the 2026-04-23 flywheel run,
 *      ~163 wells with 21K historical loads behind them.
 *
 *   2. **PCS missed-by-v2** — active PCS loads that don't resolve to a
 *      v2 assignment even after Path A bridging (shipper ticket → OCR
 *      ticket match). Live pull from the PCS sync endpoint.
 *
 * Both tabs are read-only MVP. Add/Skip/Mark actions are the Week 1
 * post-signing build.
 */

interface FlywheelWell {
  name: string;
  loads: number;
  earliest: string;
  latest: string;
  top_city: string;
  divisions: number;
  in_v2: boolean;
  classification: string;
}

interface ScopeDiscoveryResponse {
  generatedAt: string;
  flywheel: {
    stats: Record<string, unknown> | null;
    wells: FlywheelWell[];
    sandplants: FlywheelWell[];
    otherCount: number;
  };
  latestPcsSync: {
    ranAt: string;
    completedAt: string | null;
    metadata: Record<string, unknown> | null;
  } | null;
}

interface MissedByV2Entry {
  pcsLoadId: number | string;
  loadReference: string | null;
  status: string | null;
  shipperCompany?: string | null;
  shipperTicket?: string | null;
  shipperCity?: string | null;
  consigneeCompany?: string | null;
  consigneeCity?: string | null;
  pickupDate?: string | null;
  totalWeight?: string | number | null;
  milesBilled?: string | number | null;
  consigneeInV2Wells?: boolean;
  matchingBolSubmissionId?: number | null;
}

interface PcsSyncResponse {
  ranAt: string;
  pcsLoadCount: number;
  matched: number;
  unmatched: number;
  missedByV2: MissedByV2Entry[];
  bridgeable?: number;
  scopeGap?: number;
}

type Tab = "wells" | "pcs";

export function ScopeDiscovery() {
  useHeartbeat({ currentPage: "scope-discovery" });
  const [tab, setTab] = useState<Tab>("wells");
  // Shared search box at the page level — both tabs read from the
  // same `search` state so switching tabs preserves the query and a
  // dispatcher can quickly cross-reference the same string in both
  // discovery surfaces.
  const [search, setSearch] = useState("");

  const discoveryQuery = useQuery({
    queryKey: ["admin", "scope-discovery"],
    queryFn: () =>
      api.get<{
        success: boolean;
        data: ScopeDiscoveryResponse;
      }>("/diag/scope-discovery"),
    staleTime: 5 * 60_000,
  });

  return (
    <div className="flex flex-col h-full">
      {/* Page Header */}
      <div className="px-7 pt-5 pb-4 border-b border-outline-variant/40 bg-surface-container-lowest header-gradient shrink-0">
        <div className="flex items-center gap-3">
          <div className="w-1 h-8 bg-primary rounded-sm shrink-0" />
          <div>
            <h1 className="font-headline text-[22px] font-extrabold tracking-tight text-on-surface uppercase leading-tight">
              Scope Discovery
            </h1>
            <p className="text-[11px] font-medium text-outline tracking-[0.08em] uppercase mt-0.5">
              Review Queue // Wells v2 doesn't know about yet
            </p>
          </div>
        </div>
      </div>

      {/* Tab bar + search */}
      <div className="px-7 pt-4 border-b border-outline-variant/30 bg-surface-container-lowest">
        <div className="flex items-end justify-between gap-4">
          <div className="flex gap-1">
            <TabButton
              active={tab === "wells"}
              onClick={() => setTab("wells")}
              label="Wells We Discovered"
              count={discoveryQuery.data?.flywheel.wells.length}
              hint="3-year historical analysis"
            />
            <TabButton
              active={tab === "pcs"}
              onClick={() => setTab("pcs")}
              label="In PCS, Not in v2"
              hint="Live PCS reconciliation"
            />
          </div>
          <div className="relative w-full max-w-xs pb-2">
            <input
              type="search"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder={
                tab === "wells"
                  ? "Search wells, cities, classification…"
                  : "Search consignee, shipper, ticket…"
              }
              className="w-full px-3 py-1.5 text-sm rounded-md border border-outline-variant/40 bg-surface-container text-on-surface placeholder:text-on-surface-variant/60 focus:outline-none focus:ring-2 focus:ring-primary/30"
            />
            {search && (
              <button
                type="button"
                onClick={() => setSearch("")}
                className="absolute right-2 top-1/2 -translate-y-1/2 text-on-surface-variant/60 hover:text-on-surface text-xs"
                aria-label="Clear search"
                title="Clear"
              >
                ✕
              </button>
            )}
          </div>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto px-7 pt-5 pb-6 space-y-4">
        {tab === "wells" && <WellsTab query={discoveryQuery} search={search} />}
        {tab === "pcs" && <PcsTab search={search} />}
      </div>
    </div>
  );
}

function TabButton({
  active,
  onClick,
  label,
  count,
  hint,
}: {
  active: boolean;
  onClick: () => void;
  label: string;
  count?: number;
  hint?: string;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`group px-4 py-2.5 text-sm font-medium rounded-t-md border-b-2 transition-colors ${
        active
          ? "text-on-surface border-primary bg-surface-container-low"
          : "text-on-surface-variant border-transparent hover:text-on-surface hover:bg-surface-container-low/50"
      }`}
    >
      <div className="flex items-center gap-2">
        <span>{label}</span>
        {count != null && (
          <span
            className={`inline-flex items-center px-1.5 py-0.5 text-[10px] font-bold rounded-full border tabular-nums ${
              active
                ? "bg-primary/10 text-primary border-primary/30"
                : "bg-surface-container-highest text-on-surface-variant border-outline-variant/40"
            }`}
          >
            {count}
          </span>
        )}
      </div>
      {hint && (
        <div className="text-[10px] text-on-surface-variant/70 uppercase tracking-wider mt-0.5">
          {hint}
        </div>
      )}
    </button>
  );
}

/* ================================================================= */
/*  Tab 1 — Wells We Discovered                                      */
/* ================================================================= */

function WellsTab({
  query,
  search,
}: {
  query: ReturnType<typeof useQuery<ScopeDiscoveryResponse>>;
  search: string;
}) {
  // Promote a discovered well into the canonical wells registry.
  // POST /wells with needsRateInfo=true so it shows up in the
  // rate-needed view on /admin/wells immediately. Optimistically
  // tracks which names just got added so the row swaps to "✓ Added"
  // without waiting on a refetch.
  const [adding, setAdding] = useState<string | null>(null);
  const [added, setAdded] = useState<Set<string>>(new Set());
  const [addError, setAddError] = useState<string | null>(null);
  const addMutation = useMutation({
    mutationFn: (name: string) =>
      api.post<{ id: number; name: string }>("/dispatch/wells", {
        name,
        needsRateInfo: true,
      }),
    onMutate: (name) => {
      setAdding(name);
      setAddError(null);
    },
    onSuccess: (_d, name) => {
      setAdded((prev) => new Set(prev).add(name));
      setAdding(null);
    },
    onError: (err, name) => {
      setAddError(`${name}: ${(err as Error)?.message ?? "unknown error"}`);
      setAdding(null);
    },
  });

  if (query.isLoading) {
    return (
      <div className="text-sm text-on-surface-variant p-4">
        Loading flywheel discovery data…
      </div>
    );
  }
  if (query.isError) {
    return (
      <div className="text-sm text-rose-700 bg-rose-50 border border-rose-300 rounded p-4">
        Failed to load scope-discovery data:{" "}
        {(query.error as Error)?.message ?? "unknown error"}
      </div>
    );
  }
  const data = query.data;
  if (!data) return null;
  const wells = data.flywheel.wells;
  const totalLoads = wells.reduce((sum, w) => sum + w.loads, 0);

  // Substring filter against name + top_city + classification.
  const q = search.trim().toLowerCase();
  const visible = q
    ? wells.filter(
        (w) =>
          w.name.toLowerCase().includes(q) ||
          (w.top_city ?? "").toLowerCase().includes(q) ||
          (w.classification ?? "").toLowerCase().includes(q),
      )
    : wells;

  return (
    <>
      {/* Context banner */}
      <div className="bg-surface-container-lowest border border-outline-variant/40 rounded-[12px] p-5">
        <h2 className="text-base font-bold font-headline text-on-surface">
          {wells.length} wells from your history that v2 doesn't know about
        </h2>
        <p className="text-sm text-on-surface-variant mt-1 max-w-3xl">
          Generated by analyzing 3 years of historical dispatch (PropX +
          Logistiq + ES Express divisions). Each row is a distinct destination
          name the matcher saw enough times to classify as a well. Sorted by
          historical load volume — most-worked wells first.
        </p>
        <div className="flex flex-wrap gap-3 mt-3 text-[11px]">
          <StatChip label="Wells" value={wells.length.toLocaleString()} />
          <StatChip
            label="Historical loads behind them"
            value={totalLoads.toLocaleString()}
          />
          <StatChip
            label="Also detected: sandplants"
            value={data.flywheel.sandplants.length.toLocaleString()}
            dim
          />
          <StatChip
            label="Unclassified"
            value={data.flywheel.otherCount.toLocaleString()}
            dim
          />
        </div>
      </div>

      {addError && (
        <div className="text-xs text-rose-900 bg-rose-50 border border-rose-300 rounded p-2">
          Add failed: {addError}
        </div>
      )}

      {/* Wells table */}
      <div className="bg-surface-container-lowest border border-outline-variant/40 rounded-[12px] overflow-hidden">
        <div className="px-4 py-2 text-[11px] text-on-surface-variant border-b border-outline-variant/30 bg-surface-container-low/30">
          {q ? (
            <>
              Showing <strong>{visible.length}</strong> of {wells.length} wells
              matching "<strong>{search}</strong>"
            </>
          ) : (
            <>
              Showing all <strong>{wells.length}</strong> wells
            </>
          )}
        </div>
        <div className="grid grid-cols-[1fr_5.5rem_9rem_5rem_8rem_8rem] gap-3 px-4 py-2.5 text-[10px] font-bold uppercase tracking-wider text-on-surface-variant bg-surface-container-low/60 border-b border-outline-variant/40">
          <div>Well name</div>
          <div className="text-right">Loads</div>
          <div>Top city</div>
          <div className="text-center">Div</div>
          <div>Date range</div>
          <div className="text-right">Action</div>
        </div>
        {visible.length === 0 && (
          <div className="px-4 py-6 text-sm text-on-surface-variant text-center">
            No wells match "{search}".
          </div>
        )}
        {visible.map((w, i) => {
          const isAdding = adding === w.name;
          const isAdded = added.has(w.name) || w.in_v2;
          return (
            <div
              key={`${w.name}-${i}`}
              className="grid grid-cols-[1fr_5.5rem_9rem_5rem_8rem_8rem] gap-3 px-4 py-2.5 text-sm border-b border-outline-variant/20 hover:bg-surface-container-low/40 transition-colors items-center"
            >
              <div className="min-w-0">
                <div className="text-on-surface font-medium truncate">
                  {w.name}
                </div>
                <div className="text-[10px] text-on-surface-variant/70 uppercase tracking-wider">
                  {w.classification}
                </div>
              </div>
              <div className="text-right tabular-nums font-medium text-on-surface">
                {w.loads.toLocaleString()}
              </div>
              <div className="text-on-surface-variant truncate">
                {w.top_city || "—"}
              </div>
              <div className="text-center text-on-surface-variant tabular-nums">
                {w.divisions}
              </div>
              <div className="text-[11px] text-on-surface-variant/80 tabular-nums whitespace-nowrap">
                {w.earliest}
                <br />
                <span className="text-on-surface-variant/60">→ {w.latest}</span>
              </div>
              <div className="text-right">
                {isAdded ? (
                  <span
                    className="inline-flex items-center gap-1 px-2 py-1 text-[10px] font-bold uppercase tracking-wider rounded-full bg-emerald-100 text-emerald-900 border border-emerald-300"
                    title="Already in v2 wells registry"
                  >
                    ✓ In Wells
                  </span>
                ) : (
                  <button
                    type="button"
                    onClick={() => addMutation.mutate(w.name)}
                    disabled={isAdding}
                    className="px-2.5 py-1 text-[11px] font-semibold rounded-md bg-primary text-on-primary hover:opacity-90 disabled:opacity-50"
                    title="Create a v2 well with this name (needs-rate-info flagged so it shows up in the Wells admin queue)"
                  >
                    {isAdding ? "Adding…" : "+ Add to Wells"}
                  </button>
                )}
              </div>
            </div>
          );
        })}
      </div>

      <div className="text-xs text-on-surface-variant/70 text-center py-2">
        Tip: added wells land on{" "}
        <a
          href="/admin/wells"
          className="underline text-primary hover:opacity-80"
        >
          /admin/wells
        </a>{" "}
        with "needs rate info" set — finance/admin can fill the rate from there.
      </div>
    </>
  );
}

/* ================================================================= */
/*  Tab 2 — In PCS, Not in v2                                        */
/* ================================================================= */

function PcsTab({ search }: { search: string }) {
  const syncMutation = useMutation({
    mutationFn: () =>
      api.post<{
        success: boolean;
        data: PcsSyncResponse;
      }>("/pcs/sync-loads", { sinceDays: 7 }),
  });

  const data = syncMutation.data;
  const running = syncMutation.isPending;

  return (
    <>
      <div className="bg-surface-container-lowest border border-outline-variant/40 rounded-[12px] p-5">
        <h2 className="text-base font-bold font-headline text-on-surface">
          Active PCS loads with no v2 counterpart
        </h2>
        <p className="text-sm text-on-surface-variant mt-1 max-w-3xl">
          Pulls the PCS active load list (last 7 days) and attempts two bridge
          strategies: direct loadReference → v2 identifier, and Path A (PCS
          shipper ticket → OCR-extracted v2 BOL ticket). Anything that doesn't
          bridge shows below, with full shipper/consignee context so you can
          decide whether to onboard or skip.
        </p>
        <div className="flex items-center gap-3 mt-4">
          <button
            type="button"
            onClick={() => syncMutation.mutate()}
            disabled={running}
            className="px-3 py-1.5 text-sm font-semibold rounded-md bg-primary text-on-primary hover:opacity-90 disabled:opacity-50"
          >
            {running
              ? "Syncing with PCS…"
              : data
                ? "Re-run PCS sync"
                : "Run PCS sync"}
          </button>
          {data && (
            <div className="flex flex-wrap gap-2 text-[11px]">
              <StatChip label="Total PCS" value={data.pcsLoadCount} />
              <StatChip label="Matched" value={data.matched} ok />
              <StatChip label="Missed by v2" value={data.unmatched} warn />
              {data.bridgeable != null && (
                <StatChip label="Bridgeable" value={data.bridgeable} />
              )}
              {data.scopeGap != null && (
                <StatChip label="Scope gap" value={data.scopeGap} warn />
              )}
            </div>
          )}
        </div>
        {syncMutation.isError && (
          <div className="mt-3 text-xs text-rose-900 bg-rose-50 border border-rose-300 rounded p-2">
            Sync failed: {(syncMutation.error as Error).message}
          </div>
        )}
      </div>

      {!data && !running && (
        <div className="text-sm text-on-surface-variant p-4 text-center">
          Click "Run PCS sync" to fetch the current missed-by-v2 list. Fresh
          pull takes ~20 seconds (we fetch detail per load for shipper /
          consignee context).
        </div>
      )}

      {data &&
        data.missedByV2.length > 0 &&
        (() => {
          const q = search.trim().toLowerCase();
          const visible = q
            ? data.missedByV2.filter((r) =>
                [
                  r.consigneeCompany,
                  r.shipperCompany,
                  r.shipperTicket,
                  r.shipperCity,
                  r.consigneeCity,
                  r.loadReference,
                  String(r.pcsLoadId ?? ""),
                ].some((v) => (v ?? "").toString().toLowerCase().includes(q)),
              )
            : data.missedByV2;
          return (
            <>
              <div className="text-[11px] text-on-surface-variant">
                {q ? (
                  <>
                    Showing <strong>{visible.length}</strong> of{" "}
                    {data.missedByV2.length} loads matching "
                    <strong>{search}</strong>"
                  </>
                ) : (
                  <>
                    Showing all <strong>{data.missedByV2.length}</strong>{" "}
                    missed-by-v2 loads
                  </>
                )}
              </div>
              {visible.length === 0 ? (
                <div className="text-sm text-on-surface-variant p-4 text-center bg-surface-container-lowest border border-outline-variant/40 rounded-[12px]">
                  No missed-by-v2 loads match "{search}".
                </div>
              ) : (
                <MissedByV2Table rows={visible} />
              )}
            </>
          );
        })()}
      {data && data.missedByV2.length === 0 && (
        <div className="text-sm text-on-surface-variant p-6 text-center bg-surface-container-lowest border border-outline-variant/40 rounded-[12px]">
          🎯 Every active PCS load has a v2 counterpart. Nothing to review.
        </div>
      )}
    </>
  );
}

function MissedByV2Table({ rows }: { rows: MissedByV2Entry[] }) {
  // Group by consignee so dispatchers see scope gaps as single
  // onboarding decisions rather than a noisy flat list (43 loads to the
  // same well is one scope decision, not 43).
  const groups = useMemo(() => {
    const map = new Map<string, MissedByV2Entry[]>();
    for (const r of rows) {
      const key = r.consigneeCompany ?? "(unknown consignee)";
      const arr = map.get(key) ?? [];
      arr.push(r);
      map.set(key, arr);
    }
    return Array.from(map.entries()).sort((a, b) => b[1].length - a[1].length);
  }, [rows]);

  return (
    <div className="space-y-3">
      {groups.map(([consignee, entries]) => {
        const inV2 = entries[0]?.consigneeInV2Wells ?? false;
        return (
          <div
            key={consignee}
            className="bg-surface-container-lowest border border-outline-variant/40 rounded-[12px] overflow-hidden"
          >
            <div className="flex items-center justify-between gap-3 px-4 py-3 bg-surface-container-low/60 border-b border-outline-variant/40">
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2">
                  <h3 className="font-headline text-base font-bold text-on-surface truncate">
                    {consignee}
                  </h3>
                  <span
                    className={`inline-flex items-center px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider rounded-full border ${
                      inV2
                        ? "bg-emerald-100 text-emerald-900 border-emerald-300"
                        : "bg-amber-100 text-amber-900 border-amber-300"
                    }`}
                  >
                    {inV2 ? "V2 Well Exists" : "Scope Gap"}
                  </span>
                </div>
                <div className="text-[11px] text-on-surface-variant/70 mt-0.5">
                  {entries.length} PCS {entries.length === 1 ? "load" : "loads"}
                  {entries[0]?.consigneeCity
                    ? ` · ${entries[0].consigneeCity}`
                    : ""}
                </div>
              </div>
            </div>
            <div className="grid grid-cols-[1fr_8rem_9rem_6rem_6rem] gap-3 px-4 py-2 text-[10px] font-bold uppercase tracking-wider text-on-surface-variant/80 border-b border-outline-variant/30">
              <div>Shipper</div>
              <div>Ticket</div>
              <div>Pickup date</div>
              <div className="text-right">Weight</div>
              <div className="text-right">Miles</div>
            </div>
            {entries.map((e) => (
              <div
                key={`${e.pcsLoadId}`}
                className="grid grid-cols-[1fr_8rem_9rem_6rem_6rem] gap-3 px-4 py-2 text-sm border-b border-outline-variant/20 last:border-b-0 hover:bg-surface-container-low/30"
              >
                <div className="min-w-0">
                  <div className="text-on-surface truncate">
                    {e.shipperCompany ?? "—"}
                  </div>
                  <div className="text-[11px] text-on-surface-variant/70">
                    {e.shipperCity ?? ""} · PCS {String(e.pcsLoadId)}
                  </div>
                </div>
                <div className="text-on-surface-variant font-mono text-xs">
                  {e.shipperTicket ?? "—"}
                </div>
                <div className="text-on-surface-variant text-xs">
                  {e.pickupDate ?? "—"}
                </div>
                <div className="text-right tabular-nums text-on-surface-variant">
                  {e.totalWeight ? `${e.totalWeight}` : "—"}
                </div>
                <div className="text-right tabular-nums text-on-surface-variant">
                  {e.milesBilled ? `${e.milesBilled}` : "—"}
                </div>
              </div>
            ))}
          </div>
        );
      })}
    </div>
  );
}

function StatChip({
  label,
  value,
  ok,
  warn,
  dim,
}: {
  label: string;
  value: number | string;
  ok?: boolean;
  warn?: boolean;
  dim?: boolean;
}) {
  const tone = ok
    ? "bg-emerald-100 text-emerald-900 border-emerald-300"
    : warn
      ? "bg-amber-100 text-amber-900 border-amber-300"
      : dim
        ? "bg-surface-container-high text-on-surface-variant border-outline-variant/40"
        : "bg-sky-100 text-sky-900 border-sky-300";
  return (
    <span
      className={`inline-flex items-center gap-1.5 px-2 py-1 text-[11px] font-semibold rounded-full border ${tone}`}
    >
      <span className="tabular-nums">{value}</span>
      <span className="uppercase tracking-wider text-[10px] font-bold opacity-80">
        {label}
      </span>
    </span>
  );
}
